### ISSUE TITLE
Fatal error: smart media assumes all media needs cropping.

### ISSUE THREAD

**Issue by mikelittle** [humanmade/smart-media#71]
Related to https://github.com/humanmade/marketing-sites/issues/494 When a video or audio file is uploaded to block, smart media tries to crop/resize it.
It assumes `$data['media_details']['sizes']` is a valid array, but it is an empty object with these media types.
A fatal error results:

```
[31-Jul-2020 15:37:13 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /chassis/vendor/humanmade/smart-media/inc/cropper/namespace.php:146
Stack trace:
#0 /chassis/wordpress/wp-includes/class-wp-hook.php(287): HM\Media\Cropper\rest_api_fields(Object(WP_REST_Response), Object(WP_Post), Object(WP_REST_Request))
#1 /chassis/wordpress/wp-includes/plugin.php(206): WP_Hook->apply_filters(Object(WP_REST_Response), Array)
#2 /chassis/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php(544): apply_filters('rest_prepare_at...', Object(WP_REST_Response), Object(WP_Post), Object(WP_REST_Request))
#3 /chassis/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php(367): WP_REST_Attachments_Controller->prepare_item_for_response(Object(WP_Post), Object(WP_REST_Request))
#4 /chassis/wordpress/wp-includes/rest-api/class-wp-rest-server.php(1015): WP_REST_Attachments_Controller->post_process_item(Object(WP_REST_Request))
#5 /chassis/wordpress/wp-includes/rest-api/class-wp-rest-ser in /chassis/vendor/johnbillion/query-monitor/collectors/php_errors.php on line 82
```

**Comment by roborourke** [comment]
Available in 0.2.15, running `composer update altis/media --with-dependencies` will grab it, it's set to track the patch version.
